env:
  es6: true
  node: true
  jest: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended # Uses the recommended rules from the @typescript-eslint/eslint-plugin
  - prettier/@typescript-eslint # Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier
  - plugin:react/recommended
  - plugin:prettier/recommended # Enables eslint-plugin-prettier and eslint-config-prettier. This will display prettier errors as ESLint errors. Make sure this is always the last configuration in the extends array.
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/no-this-alias": 0
  "node/no-deprecated-api": 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/explicit-function-return-type':
    - off
  quotes:
    - error
    - single
